title: My very first blog
author: GitHub User
email: no-way@spam.invalid
description: > # this means to ignore newlines until "baseurl:"
  The blog to end all blogs.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
